<a href="https://colab.research.google.com/github/SandhiyaGiri/ComputerVision/blob/main/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [2]:
print(type(x_data))
print(type(data))

<class 'torch.Tensor'>
<class 'list'>


In [8]:
x_zeros = torch.zeros(2,3,)
print(x_zeros)

x_ones = torch.ones(2,3)
print(x_ones)

x_rand = torch.rand(2,3)
print(x_rand)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0221, 0.6686, 0.0310],
        [0.6479, 0.0090, 0.8449]])


In [11]:
x = torch.ones(4,4,)
print(x)
x[:,1] = 0
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [14]:
x1 = torch.cat([x,x,x],dim=1)
x1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [18]:
if torch.cuda.is_available():
  x1 = x1.to('cuda')
  print("The device is cuda")
else:
  print("The device is not cuda")

The device is cuda
